name: tek_utils

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  compile-ide:
    name: Compile IDE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build
        run: |
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: IDE
          path: ./bin/tek_utilsDistribution
